### ISSUE TITLE
Logical fails as mediator in `mma`

### ISSUE THREAD

**Issue by statisfactions** [TysonStanley/MarginalMediation#1]
When a logical variable is a mediator, `mma()` fails with an uninformative error message:

``` r
library(MarginalMediation)
#> ── MarginalMediation 0.7.0 ─────────────────────────────────────────────── learn more at tysonbarrett.com ──
#> ✓ MarginalMediation attached
#> ✓ No potential conflicts found
set.seed(100)
samp_data = data.frame(a = rnorm(n = 1000),
           b = sample(c(FALSE, TRUE), size = 1000, replace = TRUE),
           c = rnorm(n = 1000))

samp_data$b2 = factor(samp_data$b)

bcpath = glm(c ~ a + b, data = samp_data,
             family = "gaussian")
apath = glm(b ~ a, data = samp_data,
            family = "binomial")

(fit = mma(bcpath, apath,
           ind_effects = "a-b",
           boot = 10))
#> 
#> calculating a paths... b and c paths... Done.
#> Warning in norm.inter(t, alpha): extreme order statistics used as endpoints
#> Error in sort.int(x, na.last = na.last, decreasing = decreasing, ...): index 0 outside bounds
```

<sup>Created on 2021-02-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

However, the same models work just fine with a factor (shown below) or a numeric (not shown):
``` r
library(MarginalMediation)
#> ── MarginalMediation 0.7.0 ─────────────────────────────────────────────── learn more at tysonbarrett.com ──
#> ✓ MarginalMediation attached
#> ✓ No potential conflicts found
set.seed(100)
samp_data = data.frame(a = rnorm(n = 1000),
                       b = sample(c(FALSE, TRUE), size = 1000, replace = TRUE),
                       c = rnorm(n = 1000))

samp_data$b2 = factor(samp_data$b)

bcpath2 = glm(c ~ a + b2, data = samp_data,
              family = "gaussian")
apath2 = glm(b2 ~ a, data = samp_data,
             family = "binomial")

(fit2 = mma(bcpath2, apath2,
            ind_effects = "a-b2",
            boot = 10))
#> 
#> calculating a paths... b and c paths... Done.
#> Warning in norm.inter(t, alpha): extreme order statistics used as endpoints

#> Warning in norm.inter(t, alpha): extreme order statistics used as endpoints

#> Warning in norm.inter(t, alpha): extreme order statistics used as endpoints

#> Warning in norm.inter(t, alpha): extreme order statistics used as endpoints
```

    #> ┌───────────────────────────────┐
    #> │  Marginal Mediation Analysis  │
    #> └───────────────────────────────┘
    #> A marginal mediation model with:
    #>    1 mediators
    #>    1 indirect effects
    #>    1 direct effects
    #>    10 bootstrapped samples
    #>    95% confidence interval
    #>    n = 1000 
    #> 
    #> Formulas:
    #>    ◌ c ~ a + b2
    #>    ◌ b2 ~ a 
    #> 
    #> Regression Models: 
    #> 
    #>      c ~ 
    #>                          Est      SE   Est/SE P-Value
    #>         (Intercept)  0.02132 0.04469  0.47713 0.63337
    #>         a            0.03793 0.03098  1.22437 0.22110
    #>         b2TRUE      -0.03895 0.06383 -0.61021 0.54186
    #> 
    #>      b2 ~ 
    #>                          Est      SE   Est/SE P-Value
    #>         (Intercept) -0.03939 0.06328 -0.62252 0.53360
    #>         a           -0.03740 0.06144 -0.60865 0.54276
    #> 
    #> Unstandardized Mediated Effects: 
    #> 
    #>    Indirect Effects: 
    #> 
    #>      c ~ 
    #>                 Indirect    Lower   Upper
    #>         a => b2  0.00036 -0.00019 0.00604
    #> 
    #>    Direct Effects: 
    #> 
    #>      c ~ 
    #>            Direct    Lower   Upper
    #>         a 0.03793 -0.02226 0.06481
    #> 
    #> 
    #> Standardized Mediated Effects: 
    #> 
    #>    Indirect Effects: 
    #> 
    #>      c ~ 
    #>                 Indirect    Lower   Upper
    #>         a => b2  0.00036 -0.00018 0.00599
    #> 
    #>    Direct Effects: 
    #> 
    #>      c ~ 
    #>           Direct    Lower   Upper
    #>         a 0.0376 -0.02207 0.06424

<sup>Created on 2021-02-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by TysonStanley** [comment]
Thanks for the heads up on this. I'll provide an informative error for it soon.
